- name: Check Security Update
  hosts: all

  tasks:
    - name: List of package needed to update security
      shell: apt-get -s dist-upgrade | grep "^Inst" | grep -i security |
      register: Get_Security_Update_List

    - debug: var=Get_Update_List.stdout_lines

    - name: Get Number of security update
      shell: apt-get -s dist-upgrade | grep "^Inst" | grep -i security | wc -l
      register: Get_Security_Update_Number

#    - name: Install security update when needed
#      shell: apt-get -s dist-upgrade | grep "^Inst" | grep -i security | awk -F " " {'print $2'} | sudo xargs apt-get install
#      when: "'0' not in Get_Security_Update_Number.stdout_lines"
#      register: Udpate_Security_Package
