- name: Check Security Update
  hosts: all

  tasks:
    - name: List of package needed to update security
      shell: apt-get -s dist-upgrade | grep "^Inst" | grep -i security | awk -F " " {'print $2'}
      register: Get_Security_Update_List

    - debug: var=Get_Security_Update_List.stdout_lines

    - name: Get Number of security update
      shell: apt-get -s dist-upgrade | grep "^Inst" | grep -i security | wc -l
      register: Get_Security_Update_Number

    - name: Install security update when needed
      shell: apt-get -s dist-upgrade | grep "^Inst" | grep -i security | awk -F " " {'print $2'} | sudo xargs apt-get install -y
      when: "'0' not in Get_Security_Update_Number.stdout_lines"

    - name: Remove useless package dependencies
      ansible.builtin.apt:
        autoremove: yes

    - name: Remove cache of useless package
      ansible.builtin.apt:
        autoclean: yes
