---
- name: Main
  hosts: all
  tasks:
    - name: Installation Packages (Debian9)
      apt: name={{ Packages }} update_cache=yes state=latest
      when: ansible_os_family == 'Debian'
      
    - name: Installation Packages (CentOS 7)
      yum: name={{ Packages }} update_cache=yes state=latest
      when: ansible_os_family == 'RedHat'    
...
