---
- name: Simple Debug
  hosts: all
  become: yes

  tasks:
    - name: Check if Alpha.cfg exist
      ansible.builtin.shell: ls -rtl /etc/nagios/nrpe.d/
      register: Ls_Result

    - name: Print result
      ansible.builtin.debug:
        msg: Ls_Result.stdout
