# Debian 9 task

- name: [Deb 9] Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: [Deb 9] Install Fail 2 Ban package
  ansible.builtin.apt:
    name: fail2ban
    state: latest

- name: [Deb 9] Change sshd conf
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.d/defaults-debian.conf
    insertafter: 'enabled = true'
    block: |
      bantime = 1h
      findtime = 10m
      maxretry = 5
  notify: Restart Fail2Ban

- name: [Deb 9] Add DSI LAN IP to Whitelist
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/jail.conf
    regexp: "^ignoreip = 127.0.0.1/8"
    line: 'ignoreip = {{ IP_Address }}'
  notify: Restart Fail2Ban
