# Debian 10 task

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Fail 2 Ban package
  ansible.builtin.apt:
    name: fail2ban
    state: latest

- name: Change sshd conf
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.d/defaults-debian.conf
    insertafter: 'enabled = true'
    block: |
      bantime = 1h
      findtime = 10m
      maxretry = 5
  notify: Restart Fail2Ban

- name: Add DSI LAN IP to Whitelist
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/jail.conf
    insertafter: '^#ignoreip = 127.0.0.1/8 ::1'
    line: 'ignoreip = {{ IP_Address }}'
  notify: Restart Fail2Ban

handlers:
  - name: Restart Fail2Ban
    ansible.builtin.systemd:
      name: fail2ban
      enabled: yes
      state: restarted
