# Debian 10 task

- name: Deb 10 -- Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Deb 10 -- Install Fail 2 Ban package
  ansible.builtin.apt:
    name: fail2ban
    state: latest

- name: Deb 10 -- Change sshd conf
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.d/defaults-debian.conf
    insertafter: 'enabled = true'
    block: |
      bantime = 1h
      findtime = 10m
      maxretry = 5
  notify: Restart Fail2Ban

- name: Deb 10 -- Add {{ IP_Address }} to Whitelist
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/jail.conf
    insertafter: '^#ignoreip = 127.0.0.1/8 ::1'
    line: 'ignoreip = {{ IP_Address }}'
  notify: Restart Fail2Ban
  when: Action == "Add"

- name: Deb 10 -- Delete {{ IP_Address }} to Whitelist
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/jail.conf
    line: 'ignoreip = {{ IP_Address }}'
    state: absent
  notify: Restart Fail2Ban
  when: Action == "Delete"
